apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgresql-pod
      app: demo-voting-app
  template:
    metadata:
      name: postgresql-pod
      labels:
        name: postgresql-pod
        app: demo-voting-app
    spec:
      containers:
      - name: postgresql
        image: postgresql
        ports:
          - containerPort: 5432
        imagePullPolicy: Always
#        Should use secrets from vault, but this is out of scope of the current lerning example
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
