apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgresql
  template:
    metadata:
      labels:
        name: postgresql
        app: demo-voting-app
    spec:
      containers:
      - name: postgresql
        image: postgresql
        imagePullPolicy: Always
