apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app
  template:
    metadata:
      labels:
        name: voting-app
        app: demo-voting-app
    spec:
      containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:v1
        imagePullPolicy: Always
