apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        name: worker
        app: demo-voting-app
    spec:
      containers:
      - name: worker
        image: kodekloud/examplevotingapp_worker:v1
        imagePullPolicy: Always
