apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    name: postgresql-service
    app: demo-voting-app
spec:
  type: ClusterIP
  selector:
    name: postgresql
  ports:
  - port: 5432
    targetPort: 5432
